export const ADD_PRODUCT_BASKET = 'ADD_PRODUCT_BASKET'; 
export const INCREASE_QUANTITY = 'INCREASE_QUANTITY';
export const DECREASE_QUANTITY = 'DECREASE_QUANTITY';
export const CLEAR_PRODUCT = 'CLEAR_PRODUCT';
export const RESET_BASKET = 'RESET_BASKET';

export const ENJOY_PRODUCT = 'ENJOY_PRODUCT';
export const DETAILS_PRODUCT = 'DETAILS_PRODUCT';